# Generated by Django 2.2 on 2019-09-16 08:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('writed_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('categories', models.ManyToManyField(blank=True, related_name='category_sections', to='accounts.Category')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_sections', to='diaries.Diary')),
                ('references', models.ManyToManyField(blank=True, related_name='reference_sections', to='accounts.Reference')),
            ],
        ),
    ]
