# Generated by Django 2.2.4 on 2019-09-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='writed_at',
            new_name='written_at',
        ),
    ]
