# Generated by Django 2.2.4 on 2019-09-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190916_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='evaluation',
            field=models.IntegerField(blank=True, choices=[(0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], null=True),
        ),
    ]
