# Generated by Django 2.2.4 on 2019-09-25 12:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('written_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('categories', models.ManyToManyField(blank=True, related_name='category_sections', to='accounts.Category')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_sections', to='notes.Note')),
                ('references', models.ManyToManyField(blank=True, related_name='reference_sections', to='accounts.Reference')),
            ],
        ),
    ]
