# Generated by Django 2.2.4 on 2019-10-06 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='detail',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='list',
            name='next',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='todos.List'),
        ),
    ]
