# Generated by Django 2.2.4 on 2019-10-08 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20191006_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='is_archive',
        ),
        migrations.AlterField(
            model_name='list',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='todos.List'),
        ),
    ]
