# Generated by Django 2.2.4 on 2019-10-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20191013_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='detail',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
