# Generated by Django 2.2.4 on 2019-10-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20191014_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='order',
            field=models.IntegerField(default=9999),
        ),
    ]
