# Generated by Django 2.2 on 2019-09-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
