# Generated by Django 2.2 on 2019-09-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190916_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mainly_learning',
            field=models.ManyToManyField(blank=True, related_name='users', to='user.Category'),
        ),
    ]
