# Generated by Django 2.2 on 2019-09-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190916_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='learning_started_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
